"""FastAPI application factory for the time-deposit HTTP adapter.

OpenAPI/Swagger (`/docs`, `/redoc`, `/openapi.json`) is auto-generated by
FastAPI from the router's endpoints and the Pydantic response schemas --
no hand-written spec file.
"""

from fastapi import FastAPI

from adapters.inbound.http.routers import router


def create_app() -> FastAPI:
    app = FastAPI(
        title="XA Bank Time Deposit API",
        description=(
            "Recalculate and list time deposits with their withdrawals. "
            "Exposes exactly two endpoints: "
            "POST /time-deposits/update-balances and GET /time-deposits."
        ),
        version="0.1.0",
    )
    app.include_router(router)
    return app
